basePath: /
definitions:
  main.HealthResponse:
    properties:
      status:
        type: string
    type: object
  router.AuthenticationRequest:
    properties:
      ip_address:
        type: string
      password:
        type: string
      remember:
        default: false
        type: boolean
      type:
        enum:
        - password
        - mfa
        - totp
        type: string
      user_agent:
        type: string
      username:
        type: string
    required:
    - type
    type: object
  router.AuthenticationResponse:
    properties:
      session_jwt:
        type: string
    type: object
  router.ConsentCreateRequest:
    properties:
      application_id:
        type: string
      scope:
        type: string
      user_id:
        type: string
    required:
    - application_id
    - scope
    - user_id
    type: object
  router.ConsentResponse:
    properties:
      application_id:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      scope:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  router.JWKS:
    properties:
      keys:
        items:
          $ref: '#/definitions/router.JWKSKey'
        type: array
    type: object
  router.JWKSKey:
    properties:
      alg:
        type: string
      e:
        type: string
      kid:
        type: string
      kty:
        type: string
      "n":
        type: string
      use:
        type: string
    type: object
  router.PasswordHashRequest:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  router.PasswordHashResponse:
    properties:
      password_hash:
        type: string
    type: object
  router.SessionVerifyResponse:
    properties:
      expires_at:
        type: string
      user_id:
        type: string
      valid:
        type: boolean
    type: object
  router.TokenGetResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      id_token:
        type: string
      refresh_token:
        type: string
      token_type:
        type: string
    type: object
  router.TokenVerifyResponse:
    properties:
      valid:
        type: boolean
    type: object
  router.UserInfoResponse:
    properties:
      affiliation_period:
        type: string
      bio:
        type: string
      birthdate:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      name:
        type: string
      preferred_username:
        type: string
      sub:
        type: string
      twitter:
        type: string
      updated_at:
        type: integer
      website:
        type: string
    type: object
  router.WellKnownOpenIDConfigurationResponse:
    properties:
      authorization_endpoint:
        type: string
      claims_supported:
        items:
          type: string
        type: array
      code_challenge_methods_supported:
        items:
          type: string
        type: array
      grant_types_supported:
        items:
          type: string
        type: array
      id_token_signing_alg_values_supported:
        items:
          type: string
        type: array
      issuer:
        type: string
      jwks_uri:
        type: string
      response_types_supported:
        items:
          type: string
        type: array
      revocation_endpoint:
        type: string
      scopes_supported:
        items:
          type: string
        type: array
      subject_types_supported:
        items:
          type: string
        type: array
      token_endpoint:
        type: string
      token_endpoint_auth_methods_supported:
        items:
          type: string
        type: array
      userinfo_endpoint:
        type: string
    type: object
info:
  contact: {}
paths:
  /.well-known/jwks.json:
    get:
      description: .well-known/jwks.json エンドポイント
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.JWKS'
      summary: JSON Web Key Set
      tags:
      - metadata
  /.well-known/openid-configuration:
    get:
      description: .well-known/openid-configuration エンドポイント
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.WellKnownOpenIDConfigurationResponse'
      summary: OpenID Configuration
      tags:
      - metadata
  /authorization:
    get:
      description: OAuth 2.0 / OIDC における認可エンドポイントです。クライアントアプリケーションがユーザーの認可を取得するために使用します。
      parameters:
      - description: Client ID
        in: query
        name: client_id
        required: true
        type: string
      - description: Redirect URI
        in: query
        name: redirect_uri
        required: true
        type: string
      - description: Response Type
        in: query
        name: response_type
        required: true
        type: string
      - description: Scope
        in: query
        name: scope
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: string
      - description: Nonce
        in: query
        name: nonce
        type: string
      - description: Code Challenge
        in: query
        name: code_challenge
        type: string
      - description: Code Challenge Method
        in: query
        name: code_challenge_method
        type: string
      responses:
        "302":
          description: Redirect to frontend authorization page
          schema:
            type: string
      summary: authorization endpoint
      tags:
      - authorization
  /consented:
    get:
      consumes:
      - application/json
      description: 認可リクエストが完了したのちにリダイレクトするためのエンドポイントです。
      parameters:
      - description: Authorization Request ID
        in: query
        name: authorization_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "301":
          description: Redirect to client application with authorization code
          schema:
            type: string
      summary: Redirect for Authorization Request
      tags:
      - authorization
  /health:
    get:
      consumes:
      - application/json
      description: システムの稼働状況を確認するためのエンドポイントです。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.HealthResponse'
      summary: health check endpoint
      tags:
      - system info
  /internal/authentication:
    post:
      consumes:
      - application/json
      description: 内部用の認証エンドポイントです。Kubernetes / Istio の認証ポリシーにより外部からのアクセスは制限されています。
      parameters:
      - description: Authentication Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/router.AuthenticationRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.AuthenticationResponse'
      summary: authentication endpoint
      tags:
      - internal
  /internal/consents:
    get:
      consumes:
      - application/json
      description: 一覧取得およびクエリ条件による検索を行う。
      parameters:
      - description: User ID
        in: query
        name: user_id
        type: string
      - description: Application ID
        in: query
        name: application_id
        type: string
      - description: Scope
        in: query
        name: scope
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/router.ConsentResponse'
            type: array
      summary: list or search consents
      tags:
      - internal
    post:
      consumes:
      - application/json
      parameters:
      - description: Create Consent
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/router.ConsentCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/router.ConsentResponse'
      summary: create consent
      tags:
      - internal
  /internal/consents/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Consent ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: delete consent by id
      tags:
      - internal
  /internal/password_hash:
    post:
      consumes:
      - application/json
      description: パスワードのハッシュ（bcrypt）を生成する内部エンドポイント
      parameters:
      - description: Password to hash
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/router.PasswordHashRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.PasswordHashResponse'
      summary: Generate password hash
      tags:
      - internal
  /internal/session_verify:
    get:
      consumes:
      - application/json
      description: 内部用のセッション検証エンドポイントです。Kubernetes / Istio の認証ポリシーにより外部からのアクセスは制限されています。
      parameters:
      - description: JIT
        in: query
        name: jit
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.SessionVerifyResponse'
      summary: session verify endpoint
      tags:
      - internal
  /internal/token_verify:
    get:
      consumes:
      - application/json
      description: 内部用のトークン検証エンドポイントです。Kubernetes / Istio の認証ポリシーにより外部からのアクセスは制限されています。
      parameters:
      - description: JIT
        in: query
        name: jit
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.TokenVerifyResponse'
      summary: token verify endpoint
      tags:
      - internal
  /internal/update_last_logined:
    post:
      description: 内部のLastLogined更新エンドポイント
      responses:
        "201":
          description: Created
          schema:
            type: "null"
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update Last Logined
      tags:
      - internal
  /token:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: OAuth2 Token Endpoint
      parameters:
      - description: Grant Type
        enum:
        - authorization_code
        - refresh_token
        - client_credentials
        in: formData
        name: grant_type
        required: true
        type: string
      - description: Authorization Code
        in: formData
        name: code
        type: string
      - description: Redirect URI
        in: formData
        name: redirect_uri
        type: string
      - description: Client ID
        in: formData
        name: client_id
        type: string
      - description: Client Secret
        in: formData
        name: client_secret
        type: string
      - description: Refresh Token
        in: formData
        name: refresh_token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.TokenGetResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Token Endpoint
      tags:
      - oauth2
  /userinfo:
    get:
      consumes:
      - application/json
      description: OAuth2 UserInfo Endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.UserInfoResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: UserInfo Endpoint
      tags:
      - userinfo
swagger: "2.0"
