basePath: /
definitions:
  main.HealthResponse:
    properties:
      status:
        type: string
    type: object
  router.AuthenticationRequest:
    properties:
      password:
        type: string
      type:
        enum:
        - password
        - mfa
        - totp
        type: string
      username:
        type: string
    required:
    - type
    type: object
info:
  contact: {}
paths:
  /.well-known/jwks.json:
    get:
      description: .well-known/jwks.json エンドポイント
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: JSON Web Key Set
      tags:
      - Metadata
  /.well-known/openid-configuration:
    get:
      description: .well-known/openid-configuration エンドポイント
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: OpenID Configuration
      tags:
      - Metadata
  /authorization:
    get:
      description: OAuth 2.0 / OIDC における認可エンドポイントです。クライアントアプリケーションがユーザーの認可を取得するために使用します。
      parameters:
      - description: Client ID
        in: query
        name: client_id
        required: true
        type: string
      - description: Redirect URI
        in: query
        name: redirect_uri
        required: true
        type: string
      - description: Response Type
        in: query
        name: response_type
        required: true
        type: string
      - description: Scope
        in: query
        name: scope
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: string
      - description: Nonce
        in: query
        name: nonce
        type: string
      - description: Code Challenge
        in: query
        name: code_challenge
        type: string
      - description: Code Challenge Method
        in: query
        name: code_challenge_method
        type: string
      responses:
        "302":
          description: Redirect to frontend authorization page
          schema:
            type: string
      summary: authorization endpoint
      tags:
      - authorization
    post:
      consumes:
      - application/json
      description: do authorization
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: authorization endpoint
      tags:
      - authorization
  /health:
    get:
      consumes:
      - application/json
      description: システムの稼働状況を確認するためのエンドポイントです。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.HealthResponse'
      summary: health check endpoint
      tags:
      - system info
  /internal/authentication:
    post:
      description: 内部用の認証エンドポイントです。Kubernetes / Istio の認証ポリシーにより外部からのアクセスは制限されています。
      parameters:
      - description: Authentication Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/router.AuthenticationRequest'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: authentication endpoint
      tags:
      - authentication
swagger: "2.0"
