basePath: /
definitions:
  main.HealthResponse:
    properties:
      status:
        type: string
    type: object
  router.AuthenticationRequest:
    properties:
      ip_address:
        type: string
      password:
        type: string
      remember:
        default: false
        type: boolean
      type:
        enum:
        - password
        - mfa
        - totp
        type: string
      user_agent:
        type: string
      username:
        type: string
    required:
    - type
    type: object
  router.AuthenticationResponse:
    properties:
      sid:
        type: string
    type: object
  router.ConsentRequestBody:
    properties:
      approve:
        type: boolean
      auth_request_id:
        type: string
      session_id:
        type: string
    required:
    - approve
    - auth_request_id
    - session_id
    type: object
  router.ConsentResponse:
    properties:
      auth_request_id:
        type: string
    type: object
  router.JWKS:
    properties:
      keys:
        items:
          $ref: '#/definitions/router.JWKSKey'
        type: array
    type: object
  router.JWKSKey:
    properties:
      alg:
        type: string
      e:
        type: string
      kid:
        type: string
      kty:
        type: string
      "n":
        type: string
      use:
        type: string
    type: object
  router.WellKnownOpenIDConfigurationResponse:
    properties:
      authorization_endpoint:
        type: string
      claims_supported:
        items:
          type: string
        type: array
      code_challenge_methods_supported:
        items:
          type: string
        type: array
      grant_types_supported:
        items:
          type: string
        type: array
      id_token_signing_alg_values_supported:
        items:
          type: string
        type: array
      issuer:
        type: string
      jwks_uri:
        type: string
      response_types_supported:
        items:
          type: string
        type: array
      revocation_endpoint:
        type: string
      scopes_supported:
        items:
          type: string
        type: array
      subject_types_supported:
        items:
          type: string
        type: array
      token_endpoint:
        type: string
      token_endpoint_auth_methods_supported:
        items:
          type: string
        type: array
      userinfo_endpoint:
        type: string
    type: object
info:
  contact: {}
paths:
  /.well-known/jwks.json:
    get:
      description: .well-known/jwks.json エンドポイント
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.JWKS'
      summary: JSON Web Key Set
      tags:
      - metadata
  /.well-known/openid-configuration:
    get:
      description: .well-known/openid-configuration エンドポイント
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.WellKnownOpenIDConfigurationResponse'
      summary: OpenID Configuration
      tags:
      - metadata
  /authorization:
    get:
      description: OAuth 2.0 / OIDC における認可エンドポイントです。クライアントアプリケーションがユーザーの認可を取得するために使用します。
      parameters:
      - description: Client ID
        in: query
        name: client_id
        required: true
        type: string
      - description: Redirect URI
        in: query
        name: redirect_uri
        required: true
        type: string
      - description: Response Type
        in: query
        name: response_type
        required: true
        type: string
      - description: Scope
        in: query
        name: scope
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: string
      - description: Nonce
        in: query
        name: nonce
        type: string
      - description: Code Challenge
        in: query
        name: code_challenge
        type: string
      - description: Code Challenge Method
        in: query
        name: code_challenge_method
        type: string
      responses:
        "302":
          description: Redirect to frontend authorization page
          schema:
            type: string
      summary: authorization endpoint
      tags:
      - authorization
  /health:
    get:
      consumes:
      - application/json
      description: システムの稼働状況を確認するためのエンドポイントです。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.HealthResponse'
      summary: health check endpoint
      tags:
      - system info
  /internal/authentication:
    post:
      consumes:
      - application/json
      description: 内部用の認証エンドポイントです。Kubernetes / Istio の認証ポリシーにより外部からのアクセスは制限されています。
      parameters:
      - description: Authentication Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/router.AuthenticationRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.AuthenticationResponse'
      summary: authentication endpoint
      tags:
      - internal
  /internal/authorization:
    post:
      consumes:
      - application/json
      description: 内部用の認可エンドポイントです。同意したことを受け取ります。Kubernetes / Istio の認証ポリシーにより外部からのアクセスは制限されています。
      parameters:
      - description: Consent Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/router.ConsentRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.ConsentResponse'
      summary: internal consent endpoint
      tags:
      - internal
swagger: "2.0"
