name: Pylint

on: [push]

jobs:
  build:
    runs-on: k8s-runner
    container:
      image: python:3.10-slim  # pythonベースのコンテナを使用
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Git Init
      run: |
        apt update &&
        apt install git -y &&
        git config --global --add safe.directory "/__w/*"
    - uses: actions/checkout@v4
      name: Checkout the Repository
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
